import { daleChall } from "dale-chall";

export type SupportedLanguage = "english" | "italian";

export interface LanguageProfile {
    id: SupportedLanguage;
    languageName: string;
    simpleWords: Set<string>;
    stopwords: Set<string>;
    subordinateConjunctions: Set<string>;
    modalVerbs: Set<string>;
    passivePatterns: RegExp[];
    conditionTrigger: RegExp;
    conditionalHelpers: RegExp;
    technicalSuffixes: string[];
    stopwordConfidenceBoost: number;
    confidenceThreshold: number;
    penaltyFloor: number;
    penaltyBias: number;
    approximationNote: string;
}

const ENGLISH_PROFILE: LanguageProfile = {
    id: "english",
    languageName: "English",
    simpleWords: new Set(daleChall.map((word) => word.toLowerCase())),
    stopwords: new Set([
        "the",
        "and",
        "to",
        "of",
        "in",
        "for",
        "with",
        "on",
        "as",
        "at",
        "by",
        "a",
        "an",
        "be",
        "is",
        "are",
        "that",
        "this",
        "it",
        "from",
        "or",
    ]),
    subordinateConjunctions: new Set([
        "after",
        "although",
        "as",
        "because",
        "before",
        "even though",
        "if",
        "once",
        "since",
        "that",
        "though",
        "unless",
        "until",
        "when",
        "whenever",
        "where",
        "wherever",
        "while",
    ]),
    modalVerbs: new Set(["can", "could", "may", "might", "shall", "should", "will", "would", "must"]),
    passivePatterns: [
        /\b(?:am|are|is|was|were|be|been|being|has\sbeen|have\sbeen|had\sbeen|will\sbe|shall\sbe|should\sbe|would\sbe|can\sbe|could\sbe|may\sbe|might\sbe|must\sbe)\s+[a-z]+(?:ed|en)\b/gi,
    ],
    conditionTrigger: /\b(if|unless)\b/i,
    conditionalHelpers: /\b(would|could|should|might)\b/i,
    technicalSuffixes: ["tion", "sion", "ment", "ance", "ence", "ology", "ization", "isation", "ality", "iveness", "ability", "ically"],
    stopwordConfidenceBoost: 3,
    confidenceThreshold: 0.25,
    penaltyFloor: 0.35,
    penaltyBias: 0.1,
    approximationNote:
        "Language detection suggests this text is not primarily English; CEFR B2 scores are approximated using general readability heuristics.",
};

const ITALIAN_SIMPLE_WORDS = [
    "a",
    "abbastanza",
    "abbiamo",
    "abbondanza",
    "accanto",
    "accettare",
    "acqua",
    "ad",
    "adesso",
    "affare",
    "affinche",
    "agli",
    "ai",
    "aiuto",
    "al",
    "alcuni",
    "alcune",
    "all",
    "alla",
    "alle",
    "allo",
    "altre",
    "altro",
    "alto",
    "anche",
    "ancora",
    "andare",
    "andato",
    "anzi",
    "appena",
    "aprire",
    "aria",
    "arrivare",
    "arte",
    "aspetto",
    "attesa",
    "attenzione",
    "attraverso",
    "avanti",
    "avere",
    "avete",
    "avrai",
    "avremmo",
    "avrete",
    "avuto",
    "bene",
    "benche",
    "bello",
    "bisogna",
    "bisogno",
    "buono",
    "casa",
    "casi",
    "caso",
    "certo",
    "citta",
    "ci",
    "cio",
    "cioe",
    "cogliere",
    "colore",
    "come",
    "cominciare",
    "completo",
    "comprare",
    "con",
    "conoscere",
    "conto",
    "coordinare",
    "cosa",
    "cosi",
    "creare",
    "credere",
    "cui",
    "cultura",
    "da",
    "dagli",
    "dai",
    "dal",
    "dall",
    "dalla",
    "dalle",
    "dallo",
    "dare",
    "dato",
    "davanti",
    "degli",
    "dei",
    "del",
    "dell",
    "della",
    "delle",
    "dello",
    "dentro",
    "destra",
    "detto",
    "deve",
    "devono",
    "di",
    "dietro",
    "dire",
    "diretto",
    "diventa",
    "diventare",
    "diversi",
    "diverso",
    "dobbiamo",
    "dovere",
    "dopo",
    "dove",
    "dover",
    "ebraico",
    "egli",
    "elemento",
    "entrambi",
    "entra",
    "entrare",
    "entro",
    "essa",
    "esso",
    "estero",
    "e",
    "faccia",
    "facile",
    "fanno",
    "fare",
    "fatto",
    "favore",
    "fino",
    "finche",
    "forma",
    "forse",
    "forza",
    "fotografia",
    "fra",
    "futuro",
    "gia",
    "gioco",
    "giorni",
    "giorno",
    "gia",
    "giovane",
    "gli",
    "governo",
    "grazie",
    "grande",
    "gruppo",
    "ha",
    "hanno",
    "ho",
    "ieri",
    "il",
    "imparare",
    "in",
    "incontrare",
    "infatti",
    "infine",
    "insieme",
    "inoltre",
    "intanto",
    "intorno",
    "introdurre",
    "io",
    "lavorare",
    "lavoro",
    "lei",
    "li",
    "libero",
    "libro",
    "lontano",
    "loro",
    "lo",
    "luogo",
    "lui",
    "lungo",
    "ma",
    "macchina",
    "magari",
    "maggiore",
    "mai",
    "male",
    "mano",
    "mare",
    "meglio",
    "memoria",
    "meno",
    "mentre",
    "merito",
    "mesi",
    "messaggio",
    "mezzo",
    "mia",
    "mio",
    "modo",
    "molti",
    "molto",
    "mondo",
    "momento",
    "mora",
    "morire",
    "motivo",
    "movimento",
    "nazionale",
    "nei",
    "nel",
    "nell",
    "nella",
    "nelle",
    "nello",
    "nero",
    "nessuno",
    "noi",
    "nome",
    "non",
    "nostra",
    "nostro",
    "nuovo",
    "numero",
    "o",
    "oggi",
    "ogni",
    "ognuno",
    "opera",
    "oppure",
    "ora",
    "oscuro",
    "paese",
    "pagare",
    "parlare",
    "parte",
    "partire",
    "per",
    "perche",
    "percio",
    "perfino",
    "persona",
    "piace",
    "piacere",
    "piangere",
    "piu",
    "po",
    "poiche",
    "possiamo",
    "posso",
    "possibile",
    "possibilita",
    "posto",
    "potere",
    "poveri",
    "povero",
    "presso",
    "presto",
    "prima",
    "primo",
    "problema",
    "proprio",
    "prossimo",
    "prova",
    "provare",
    "punto",
    "quanto",
    "quasi",
    "quel",
    "quella",
    "quelle",
    "quello",
    "quest",
    "questa",
    "queste",
    "questi",
    "questo",
    "qui",
    "quindi",
    "realta",
    "resto",
    "ricerca",
    "ricordare",
    "ricordo",
    "rispetto",
    "risposta",
    "sapere",
    "sarebbe",
    "saremo",
    "sarei",
    "saranno",
    "sara",
    "saro",
    "sbaglio",
    "scala",
    "scarso",
    "scelta",
    "scendere",
    "scopo",
    "scuola",
    "se",
    "secondo",
    "seguire",
    "semplice",
    "sempre",
    "senza",
    "sera",
    "serie",
    "serio",
    "servizio",
    "sezione",
    "si",
    "sistema",
    "situazione",
    "societa",
    "sopra",
    "soprattutto",
    "sotto",
    "spazio",
    "sperare",
    "speriamo",
    "spesso",
    "spingere",
    "sposare",
    "stanca",
    "stare",
    "stata",
    "state",
    "stati",
    "stato",
    "stessa",
    "stesso",
    "storia",
    "strada",
    "strumento",
    "studio",
    "successo",
    "sui",
    "sul",
    "sull",
    "sulla",
    "sulle",
    "sullo",
    "suo",
    "suoi",
    "superare",
    "su",
    "talmente",
    "tanto",
    "te",
    "tempo",
    "tenda",
    "tenere",
    "terra",
    "tiene",
    "tieni",
    "togliere",
    "torna",
    "tornare",
    "tra",
    "trovare",
    "tu",
    "tua",
    "tuo",
    "tutti",
    "tutto",
    "uguale",
    "uomo",
    "uscire",
    "utile",
    "va",
    "vai",
    "valore",
    "vedere",
    "vela",
    "venire",
    "vento",
    "vera",
    "vero",
    "verso",
    "vi",
    "via",
    "vicino",
    "vita",
    "vivo",
    "volere",
    "volta",
    "vostro",
];

const ITALIAN_STOPWORDS = [
    "a",
    "abbia",
    "abbiamo",
    "abbiano",
    "abbiate",
    "accanto",
    "ad",
    "adesso",
    "agl",
    "agli",
    "ai",
    "al",
    "all",
    "alla",
    "alle",
    "allo",
    "anche",
    "ancora",
    "avere",
    "avete",
    "aveva",
    "avevano",
    "avevo",
    "avrai",
    "avranno",
    "avrebbe",
    "avrei",
    "avremo",
    "avreste",
    "avro",
    "benche",
    "cio",
    "cioe",
    "coi",
    "col",
    "come",
    "con",
    "contro",
    "cui",
    "da",
    "dagli",
    "dai",
    "dal",
    "dall",
    "dalla",
    "dalle",
    "dallo",
    "degl",
    "degli",
    "dei",
    "del",
    "dell",
    "della",
    "delle",
    "dello",
    "dentro",
    "di",
    "dopo",
    "dove",
    "ecc",
    "ed",
    "e",
    "faccio",
    "fai",
    "fanno",
    "fare",
    "farai",
    "faranno",
    "farebbe",
    "farei",
    "faremo",
    "fareste",
    "farla",
    "farlo",
    "faro",
    "forse",
    "fra",
    "gia",
    "gli",
    "ha",
    "hai",
    "hanno",
    "ho",
    "in",
    "insieme",
    "io",
    "l",
    "la",
    "le",
    "lei",
    "li",
    "lo",
    "loro",
    "lui",
    "ma",
    "mai",
    "me",
    "mentre",
    "mi",
    "mia",
    "mie",
    "miei",
    "mio",
    "ne",
    "negli",
    "nei",
    "nel",
    "nell",
    "nella",
    "nelle",
    "nello",
    "no",
    "noi",
    "non",
    "nostra",
    "nostre",
    "nostri",
    "nostro",
    "o",
    "oppure",
    "per",
    "pero",
    "piu",
    "poiche",
    "poi",
    "potrebbe",
    "potremmo",
    "potreste",
    "potro",
    "potranno",
    "potrei",
    "potremmo",
    "potrete",
    "potrebbero",
    "puo",
    "quale",
    "quali",
    "quando",
    "quanto",
    "quasi",
    "quel",
    "quella",
    "quelle",
    "quello",
    "quest",
    "questa",
    "queste",
    "questi",
    "questo",
    "sia",
    "siamo",
    "siano",
    "siate",
    "si",
    "solo",
    "sono",
    "sopra",
    "sotto",
    "sua",
    "sue",
    "sui",
    "sul",
    "sull",
    "sulla",
    "sulle",
    "sullo",
    "suo",
    "suoi",
    "tra",
    "troppo",
    "tu",
    "tua",
    "tue",
    "tuo",
    "tuoi",
    "tutti",
    "tutto",
    "un",
    "una",
    "uno",
    "vi",
];

const ITALIAN_SUBORDINATE_CONJUNCTIONS = [
    "affinche",
    "anche se",
    "benche",
    "che",
    "come",
    "dopo che",
    "finche",
    "mentre",
    "non appena",
    "perche",
    "poiche",
    "prima che",
    "qualora",
    "se",
    "sebbene",
    "siccome",
    "visto che",
];

const ITALIAN_MODAL_VERBS = [
    "posso",
    "puoi",
    "puo",
    "possiamo",
    "potete",
    "possono",
    "potrei",
    "potresti",
    "potrebbe",
    "potremmo",
    "potreste",
    "potrebbero",
    "devo",
    "devi",
    "deve",
    "dobbiamo",
    "dovete",
    "devono",
    "dovrei",
    "dovresti",
    "dovrebbe",
    "dovremmo",
    "dovreste",
    "dovrebbero",
    "voglio",
    "vuoi",
    "vuole",
    "vogliamo",
    "volete",
    "vogliono",
    "vorrei",
    "vorresti",
    "vorrebbe",
    "vorremmo",
    "vorreste",
    "vorrebbero",
    "so",
    "sai",
    "sa",
    "sappiamo",
    "sapete",
    "sanno",
];

const ITALIAN_PASSIVE_PATTERNS = [
    /\b(?:sono|sei|sei|e|siamo|siete|ero|eri|era|erano|fui|fu|furono|sarai|sara|saranno|saro|saremmo|sarebbe|sarebbero|siano|sia|fosse|fossero|veniva|venivano|viene|vengono|verra|verranno|verrebbe|verrebbero)\s+\w+(?:to|ta|ti|te)\b/gi,
    /\b(?:e|era|sara|saranno|viene|veniva)\s+stato\s+\w+(?:to|ta|ti|te)\b/gi,
];

const ITALIAN_CONDITION_TRIGGER = /\bse\b/i;
const ITALIAN_CONDITIONAL_HELPERS =
    /\b(?:potrei|potresti|potrebbe|potremmo|potreste|potrebbero|dovrei|dovresti|dovrebbe|dovremmo|dovreste|dovrebbero|farei|farebbe|farebbero|sarei|sarebbe|sarebbero|avrei|avrebbe|avrebbero|andrei|andrebbe|andrebbero)\b/i;

const ITALIAN_PROFILE: LanguageProfile = {
    id: "italian",
    languageName: "Italian",
    simpleWords: new Set(ITALIAN_SIMPLE_WORDS),
    stopwords: new Set(ITALIAN_STOPWORDS),
    subordinateConjunctions: new Set(ITALIAN_SUBORDINATE_CONJUNCTIONS),
    modalVerbs: new Set(ITALIAN_MODAL_VERBS),
    passivePatterns: ITALIAN_PASSIVE_PATTERNS,
    conditionTrigger: ITALIAN_CONDITION_TRIGGER,
    conditionalHelpers: ITALIAN_CONDITIONAL_HELPERS,
    technicalSuffixes: [
        "zione",
        "sione",
        "mento",
        "amento",
        "imento",
        "logia",
        "izzare",
        "izzazione",
        "istica",
        "istico",
        "mente",
        "tore",
        "trice",
        "cita",
        "ita",
        "enza",
        "anza",
        "ario",
        "eria",
        "eggio",
        "atore",
        "atrice",
        "tura",
        "aggio",
    ],
    stopwordConfidenceBoost: 2.5,
    confidenceThreshold: 0.2,
    penaltyFloor: 0.45,
    penaltyBias: 0.12,
    approximationNote:
        "Language detection suggests this text is not primarily Italian; CEFR B2 scores are approximated using localized heuristics.",
};

const LANGUAGE_PROFILES: Record<SupportedLanguage, LanguageProfile> = {
    english: ENGLISH_PROFILE,
    italian: ITALIAN_PROFILE,
};

const LANGUAGE_ALIASES = new Map<string, SupportedLanguage>([
    ["en", "english"],
    ["eng", "english"],
    ["english", "english"],
    ["en-us", "english"],
    ["en-gb", "english"],
    ["it", "italian"],
    ["ita", "italian"],
    ["italian", "italian"],
    ["italiano", "italian"],
]);

export function resolveLanguageProfile(language?: string): LanguageProfile {
    if (!language) {
        return LANGUAGE_PROFILES.english;
    }
    const normalized = language.trim().toLowerCase();
    const mapped = LANGUAGE_ALIASES.get(normalized);
    if (mapped) {
        return LANGUAGE_PROFILES[mapped];
    }
    return LANGUAGE_PROFILES.english;
}


